# Generated by Django 4.2 on 2024-07-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Electric'), ('G', 'Grass'), ('R', 'Rock'), ('W', 'Water'), ('I', 'Ice'), ('G', 'Ground'), ('F', 'Fire'), ('N', 'Normal')], max_length=15),
        ),
    ]
