# Generated by Django 4.2 on 2024-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Electric'), ('GR', 'Ground'), ('W', 'Water'), ('I', 'Ice'), ('F', 'Fire'), ('R', 'Rock'), ('N', 'Normal'), ('G', 'Grass')], max_length=15),
        ),
    ]
