# Generated by Django 4.2 on 2024-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='region',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
