# Generated by Django 4.2 on 2024-07-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='region',
            field=models.CharField(max_length=30),
        ),
    ]
